### ISSUE TITLE
Hello just a random wanderer here ! you said that you have integrated stripe but i am not able to see it 

### ISSUE THREAD

**Issue by abhijit-23blaze** [vinayak700/Shopify#1]
currently you are using brain tree are you planning to change it to stripe ?

**Comment by vinayak700** [comment]
Sorry for the inconvenience, I have not pushed the updated local repo to
the github since it's subscription based.
Don't worry, I will get this done my tomorrow!!!

**Comment by abhijit-23blaze** [comment]
Great!! I was working on a project and was having trouble integrating stripe that's why i asked

**Comment by abhijit-23blaze** [comment]
looking forward to it

**Comment by abhijit-23blaze** [comment]
also can you tell me about the .env file on the client side as well ?

**Comment by vinayak700** [comment]
What do you wanna know exactly pin them down here?
I will try to assist you as much as I can!

**Comment by abhijit-23blaze** [comment]
so firstly i think i have connected it correctly to monodb but when i try to login i am not able to

**Comment by vinayak700** [comment]
1.Try to import and load dotenv and log it inside your database
configuration file and check the result.(process.env.'your_env')
2.Check that you correctly specify env variables (it always starts with
REACT_APP_'YOUR_ENV') for client side.

**Comment by abhijit-23blaze** [comment]
right is but what is the api url is it the mango db url ?? i always work with firebase this is my first time working with mongo db that's why i am asking

**Comment by vinayak700** [comment]
local:  mongodb://localhost:27017/<database>
mongoAtlas : mongodb+srv://<username>:<password>@
cluster0.khgpbvj.mongodb.net
replace username and password with yours
(check the password conversion nomenclature for special characters before
putting it)

**Comment by vinayak700** [comment]
(correction)
mongodb Atlas:  "mongodb+srv://<username>:<password>@<clusterName>.
mongodb.net/?retryWrites=true&w=majority"
